version: '2'
volumes:
    data:
services:
  influxdb:
    restart: always
    build: ./etcher-pro-monitoring/influxdb
    volumes:
      - 'data:/data'
    ports:
            - "8086:8086"
  grafana:
    restart: always
    build: ./etcher-pro-monitoring/grafana
    ports:
      - "80:80"
    volumes:
      - 'data:/data'
    environment:
        - 'GF_SERVER_HTTP_PORT=80'
        - 'GF_PATHS_PROVISIONING=/usr/src/app/provisioning'
        - 'GF_SESSION_PROVIDER=memory'
  collectd:
    build: ./etcher-pro-monitoring/collectd
    privileged: true  # needed ?
    restart: always
  beep:
    build: ./etcher-pro-monitoring/beep
    privileged: true
    restart: no
  benchmark:
    build: ./etcher-pro-monitoring/benchmark
    privileged: true
    restart: always
  etcher:
    build: .
    privileged: true
    restart: always
    labels:
      io.balena.features.dbus: 1
