{
 "title": "Status",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "Thermal zone 0",
     "measurement": "thermal_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "thermal_zone0" }
     ]
    },
    {
     "alias": "Thermal zone 1",
     "measurement": "thermal_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "thermal_zone1" }
     ]
    }
   ]
  },
  {
   "title": "data partition usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "type_instance" ], "type": "tag" }
     ],
     "measurement": "df_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "etc-hosts" }
     ]
    }
   ]
  },
  {
   "title": "eMMC read",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "disk_write",
     "query": "SELECT derivative(\"value\", 1s) FROM \"disk_read\" WHERE (\"type\" = 'disk_octets' AND (\"instance\" = 'mmcblk0boot0' OR \"instance\" = 'mmcblk0boot1' OR \"instance\" = 'mmcblk0p1' OR \"instance\" = 'mmcblk0p2' OR \"instance\" = 'mmcblk0p3' OR \"instance\" = 'mmcblk0p4' OR \"instance\" = 'mmcblk0p5' OR \"instance\" = 'mmcblk0p6')) AND $timeFilter GROUP BY \"instance\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "disk_octets" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sda" },
      { "condition": "OR", "key": "instance", "operator": "=", "value": "sdb" }
     ]
    }
   ]
  },
  {
   "title": "eMMC write",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "disk_write",
     "query": "SELECT derivative(\"value\", 1s) FROM \"disk_write\" WHERE (\"type\" = 'disk_octets' AND (\"instance\" = 'mmcblk0boot0' OR \"instance\" = 'mmcblk0boot1' OR \"instance\" = 'mmcblk0p1' OR \"instance\" = 'mmcblk0p2' OR \"instance\" = 'mmcblk0p3' OR \"instance\" = 'mmcblk0p4' OR \"instance\" = 'mmcblk0p5' OR \"instance\" = 'mmcblk0p6')) AND $timeFilter GROUP BY \"instance\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "disk_octets" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sda" },
      { "condition": "OR", "key": "instance", "operator": "=", "value": "sdb" }
     ]
    }
   ]
  },
  {
   "title": "Disk read",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "disk_write",
     "query": "SELECT derivative(\"value\", 1s) FROM \"disk_read\" WHERE (\"type\" = 'disk_octets' AND (\"instance\" = 'sda' OR \"instance\" = 'sdb' OR \"instance\" = 'sdc' OR \"instance\" = 'sdd' OR \"instance\" = 'sde' OR \"instance\" = 'sdf' OR \"instance\" = 'sdg' OR \"instance\" = 'sdh' OR \"instance\" = 'sdi' OR \"instance\" = 'sdj' OR \"instance\" = 'sdk' OR \"instance\" = 'sdl' OR \"instance\" = 'sdm' OR \"instance\" = 'sdn' OR \"instance\" = 'sdo' OR \"instance\" = 'sdp')) AND $timeFilter GROUP BY \"instance\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "disk_octets" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sda" },
      { "condition": "OR", "key": "instance", "operator": "=", "value": "sdb" }
     ]
    }
   ]
  },
  {
   "title": "Disk write",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "disk_write",
     "query": "SELECT derivative(\"value\", 1s) FROM \"disk_write\" WHERE (\"type\" = 'disk_octets' AND (\"instance\" = 'sda' OR \"instance\" = 'sdb' OR \"instance\" = 'sdc' OR \"instance\" = 'sdd' OR \"instance\" = 'sde' OR \"instance\" = 'sdf' OR \"instance\" = 'sdg' OR \"instance\" = 'sdh' OR \"instance\" = 'sdi' OR \"instance\" = 'sdj' OR \"instance\" = 'sdk' OR \"instance\" = 'sdl' OR \"instance\" = 'sdm' OR \"instance\" = 'sdn' OR \"instance\" = 'sdo' OR \"instance\" = 'sdp')) AND $timeFilter GROUP BY \"instance\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "disk_octets" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sda" },
      { "condition": "OR", "key": "instance", "operator": "=", "value": "sdb" }
     ]
    }
   ]
  },
  {
   "title": "System load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "load_shortterm",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "load_midterm",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "load_longterm",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "type_instance" ], "type": "tag" }
     ],
     "measurement": "memory_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU 0",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "type_instance" ], "type": "tag" }
     ],
     "measurement": "cpu_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "0" },
      { "condition": "AND", "key": "type_instance", "operator": "!=", "value": "idle" }
     ]
    }
   ]
  },
  {
   "title": "CPU 1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "type_instance" ], "type": "tag" }
     ],
     "measurement": "cpu_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "1" },
      { "condition": "AND", "key": "type_instance", "operator": "!=", "value": "idle" }
     ]
    }
   ]
  },
  {
   "title": "CPU 2",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "type_instance" ], "type": "tag" }
     ],
     "measurement": "cpu_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "2" },
      { "condition": "AND", "key": "type_instance", "operator": "!=", "value": "idle" }
     ]
    }
   ]
  },
  {
   "title": "CPU 3",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "type_instance" ], "type": "tag" }
     ],
     "measurement": "cpu_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "3" },
      { "condition": "AND", "key": "type_instance", "operator": "!=", "value": "idle" }
     ]
    }
   ]
  }
 ]
}